server:
  port: 8065

# 存储 DataAgent 业务数据的数据库，并非Agent分析数据的来源
spring:
  datasource:
    url: ${DATA_AGENT_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/data_agent?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${DATA_AGENT_DATASOURCE_USERNAME:root}
    password: ${DATA_AGENT_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  sql:
    init:
      mode: never
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      continue-on-error: true
      separator: ;
      encoding: utf-8
  ai:
    vectorstore:
      type: milvus
      milvus:
        database-name: MyAgent
        client:

          host: 192.168.232.128

    mcp:
      server:
        enabled: true
        transport: sse
    #        sse-endpoint: /mcp/message
    #        sse:
    #          path: /mcp/message
    #    dashscope:
    #      api-key: sk-ae719b66dda4478bab9d8c84b360f812
    #      chat:
    #        enabled: false
    #        options:
    #          model: qwen3-max
    #      embedding:
    #        enabled: false
    #        options:
    #          model: qwen3-rerank
    zhipuai:
      api-key: 83f34996de3a45f892d8f619efcade33.rzqfEAbw48hy5705
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model: glm-4.5
    alibaba:
      data-agent:
        llm-service-type: stream
        code-executor:
          # 运行Python代码的环境（生产环境建议使用docker，不建议使用local）
          code-pool-executor: local
        file:
          type: local
          path-prefix: data-agent
          path: ./uploads
          url-prefix: /uploads
          imageSize: 2097152
          oss:
            access-key-id: ${OSS_ACCESS_KEY_ID:}
            access-key-secret: ${OSS_ACCESS_KEY_SECRET:}
            endpoint: ${OSS_ENDPOINT:}
            bucket-name: ${OSS_BUCKET_NAME:}
            custom-domain: ${OSS_CUSTOM_DOMAIN:}
        max-sql-retry-count: 5
        max-sql-optimize-count: 5
        sql-score-threshold: 0.8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 日志配置
logging:
  level:
    com.alibaba.cloud.ai.mapper: debug
    org.springframework.jdbc: debug
